### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by LaviniaYu** [Ashish7129/Graph_Sampling#12]
**Installation failed**
I followed your instructions:
1. git clone https://github.com/Ashish7129/Graph-Sampling.git
2. cd Sampling
3. pip install -e
4. See error:
![image](https://user-images.githubusercontent.com/34830118/49583210-6d5aaa80-f992-11e8-9f5d-df35c6645484.png)

**I tried the second way**
1.download the zip file and move to its directory.
2.pip install Sampling
3.See error:
![image](https://user-images.githubusercontent.com/34830118/49583316-c62a4300-f992-11e8-8d94-a67bfa15848b.png)

--macOS python2.7

**Comment by peterbengkui** [comment]
Looks like the authors are on the process of transiting from py2 to py3

**Comment by Ashish7129** [comment]
Hi all, have a look to the updated version ( Only for python 3)
