### ISSUE TITLE
Confusion with the probability in MHRW

### ISSUE THREAD

**Issue by Jasmineysj** [Ashish7129/Graph_Sampling#14]
In the implementation of MHRW 
```python
        while(len(self.G1.nodes()) < size):
            if(len(node_list) > 0):
                child_node = node_list.pop()
                p =  round(random.uniform(0,1),4)
                if(child_node not in dictt):
                    related_listt = list(G.neighbors(child_node))
                    degree_c = G.degree(child_node)
                    dictt[child_node] = child_node
                    if(p <= min(1,degree_p/degree_c) and child_node in list(G.neighbors(parent_node))):
                        self.G1.add_edge(parent_node,child_node)
                        parent_node = child_node
                        degree_p = degree_c
                        node_list.clear()
                        node_list.update(related_listt)
                    else:
                        del dictt[child_node]
```
The probability of walking from parent_node to child_node seems to be `min(1,degree_p/degree_c)` but in the [paper](https://ronghuali.github.io/paper/icde15rw.pdf) the probability should be `parent_node.deg() * min(1,degree_p/degree_c)`, which is not consistent

**Comment by Ashish7129** [comment]
Hey Jasmineysj,
We are also in the research phase for MHRW. There are a few things which we also need to find as per the condition of probability. Every other research paper says different and inconsistent technique for MHRW. You can change according to your requirements and knowledge.

Thanks

**Comment by Jasmineysj** [comment]
Okay, thanks
